// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qennrndhjqqbysbwqfqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlbm5ybmRoanFxYnlzYndxZnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTUwNTksImV4cCI6MjA2MjgzMTA1OX0.pdhiYDq7_XWUCAoAJtcTk3vIgRL_LDHMKwn1Xewx95c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);